name = "DUP MC 1.21"
author = "dirtTW"
version = "0.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a628bf1171a2878bb708d5864de0b6e97940363a4de425f97cb07d527f3a8c60"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
