name = "DUP MC 1.21"
author = "dirtTW"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff6e545c3a4707546994fa8389132e776a01bf9fce1d4cfd1a4e339de3f6d079"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
