name = "DUP MC 1.21"
author = "dirtTW"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12eecef989c27fc454877011d3eb1a5cac1bd71c9df02b3f7ac3559cc4715a9c"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
