name = "DUP MC 1.21"
author = "dirtTW"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9126ace1e36bb1c46b4614e0099e3a6363f80997f06d96cfd2e9cb346d4cc499"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
