name = "DUP MC 1.20.4"
author = "dirtTW"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb14b065b5699ad2d9a04cc32749d856d4ae5c097c23d07708a5bd7ac78ff26a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
