name = "DUP"
author = "dirtTW"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bee91b5814b982693567b43b7dd48f077a37d04e91ecda9a5e70fd5211eb4055"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
