name = "DUP MC 1.21.4"
author = "dirtTW"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b3f5d7607a97ff458b25ee9cf0502b8debeaf0ba81a2e30027cf6d888c41f0b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
