name = "DUP MC 1.21.4"
author = "dirtTW"
version = "0.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a90e46879edd05debfcbac3988ffc2d5b7738b9b098a2f3b3fd8b757905ffc9e"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
