name = "DUP MC 1.21.1"
author = "dirtTW"
version = "0.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a84b9c7327ec0148200c3d4e29645dc56eb3a6aff587ae202407cc615223e4e3"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"
