name = "DUP"
author = "dirtTW"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4176129aa8cf4da8775d13911cc230bcbc9d092b8b588b322b94c63415955532"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
