name = "DUP"
author = "dirtTW"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6c50d965a5fb578c78745eb4f84f751746538586971ae4e64aa305558dd30cc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
