name = "DUP"
author = "dirtTW"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8db7893ee5add8c64c7bbc8b2003c514b6d3a242c3bc1839c2504d3c2a0ffa2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
